stages:
  load_data:
    cmd: python src/stage_01_data_ingestion.py --config=config/config.yaml
    deps: 
      - src/stage_01_data_ingestion.py
      - src/utils/all_utils.py
      - config/config.yaml
    outs:
      - Artifacts/raw_data/ct_scan/
      - logs/stage_01_log.log

  prepare_base_model:
    cmd: python src/stage_02_prepare_base_model.py --config=config/config.yaml --params=params.yaml
    deps: 
      - src/stage_02_prepare_base_model.py
      - src/utils/all_utils.py
      - src/utils/models.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - LEARNING_RATE
    outs:
      - artifacts/base_model/updated_inception_ct.h5
      - artifacts/base_model/inception_ct.h5
      - logs/stage_02_log.log

  prepare_callbacks:
    cmd: python src/stage_03_prepare_callbacks.py --config=config/config.yaml --params=params.yaml
    deps: 
      - src/stage_03_prepare_callbacks.py
      - src/utils/all_utils.py
      - src/utils/callbacks.py
      - config/config.yaml
    outs:
      - artifacts/callbacks/checkpoint_cb.cb
      - artifacts/callbacks/tensorboard_cb.cb
      - logs/stage_03_log.log
      

  train:
    cmd: python src/stage_04_train.py --config=config/config.yaml --params=params.yaml
    deps: 
      - src/stage_04_train.py
      - src/utils/all_utils.py
      - src/utils/models.py
      - src/utils/callbacks.py
      - src/utils/data_management.py
      - config/config.yaml
      - Artifacts/raw_data/ct_scan/
      - artifacts/base_model/updated_inception_ct.h5
      - artifacts/callbacks/checkpoint_cb.cb
      - artifacts/callbacks/tensorboard_cb.cb
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
      - EPOCHS
      - AUGMENTATION
    outs:
      - artifacts/model
      - Artifacts/checkpoints/ckpt_model.h5
      - Artifacts/tensorboard_log_dir/
      - logs/stage_04_log.log
